# Generated by Django 3.2.23 on 2024-06-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240603_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('date_of_review', models.DateField()),
                ('sentiment', models.CharField(max_length=100)),
                ('sentiment_score', models.CharField(max_length=100)),
            ],
        ),
    ]
