# Generated by Django 3.2.23 on 2024-06-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_sentimentanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
