# Generated by Django 3.2.23 on 2024-06-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20240618_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
