# Generated by Django 3.2.23 on 2024-06-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_qauntity_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
